/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadnetwork.gui;

import java.sql.SQLRecoverableException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import roadnetwork.controllers.CreateSimulationController;

/**
 *
 * @author antonio
 */
public class CreateSimulationFrame extends javax.swing.JFrame {

    MainFrame m_mainFrame;
    CreateSimulationController m_createSimulationController;
    

    public CreateSimulationFrame(MainFrame frame) {
        m_mainFrame = frame;
        m_createSimulationController = new CreateSimulationController(frame.getManager());
        if(m_createSimulationController.newSimulation()){
            initComponents();
            setContentPane(new CreateSimulationPane(this));
            setLocationRelativeTo(null);
            pack();
            setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Please create a project first.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void createSimulation(String name, String description, String filepath) {
        try {
            if (!m_createSimulationController.simulationExists(name)) {
                m_createSimulationController.setSimulation(name, description);
                if (m_createSimulationController.setTrafficFile(filepath)) {
                    JOptionPane.showMessageDialog(this, "Simulation created with success.");
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "An error was found while load traffic pattern file. Please try again.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "This simulation already exists.");
            }
        } catch (SQLRecoverableException ex) {
            JOptionPane.showMessageDialog(this, "Error found while trying to connect to database. Please try again.", "Database Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(CreateSimulationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
