/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadnetwork.gui;

import java.sql.SQLRecoverableException;
import javax.swing.JOptionPane;
import roadnetwork.controllers.EditProjectPropertiesController;
import roadnetwork.domain.Project;

/**
 *
 * @author André Pedrosa, Hélder Faria, José Miranda, Rubén Rosário
 */
public class EditProjectPropertiesFrame extends javax.swing.JFrame {

    MainFrame m_mainFrame;
    EditProjectPropertiesController m_editProjectPropertiesController;
    String m_oldName;
    String m_oldDescription;

    /**
     * Creates new form EditProjectPropertiesFrame
     */
    public EditProjectPropertiesFrame(MainFrame mainFrame) {
        m_mainFrame = mainFrame;
        m_editProjectPropertiesController = new EditProjectPropertiesController(mainFrame.getManager());

        run();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void newProperties(String newName, String newDescription) {
        if (m_editProjectPropertiesController.setNewProperties(newName, newDescription)) {
            JOptionPane.showMessageDialog(this, "Properties have been changed.", "Properties changed", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "There was an error!\n"
                    + " Properties Not changed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void run() {

        if (!m_editProjectPropertiesController.projectActive()) {
            JOptionPane.showMessageDialog(this, "Can't view or edit properties. There is no active project.", "No active project", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else if (m_editProjectPropertiesController.editProperties()) {

            m_oldName = m_editProjectPropertiesController.getProjectName();
            m_oldDescription = m_editProjectPropertiesController.getProjectDescription();
            initComponents();
            setContentPane(new EditProjectPropertiesPane(this, m_oldName, m_oldDescription));
            setLocationRelativeTo(null);
            setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Can't edit properties.", "Error", JOptionPane.ERROR_MESSAGE);
            setVisible(false);
        }
    }

    boolean nameExists(String name) throws SQLRecoverableException {
        return m_editProjectPropertiesController.nameExists(name);
    }
}
