/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadnetwork.gui;

import javax.swing.JOptionPane;
import roadnetwork.controllers.EditSimulationPropertiesController;

/**
 *
 * @author André Pedrosa, Hélder Faria, José Miranda, Rubén Rosário
 */
public class EditSimulationPropertiesDialog extends javax.swing.JDialog {

    private MainFrame m_ancestor;
    private EditSimulationPropertiesController m_editSimProppertiesController;
    private String m_oldName;
    private String m_oldDescription;

    /**
     * Creates new form EditSimulationPropertiesDialog
     */
    public EditSimulationPropertiesDialog(MainFrame mainFrame, boolean modal) {
        super(mainFrame, modal);
        m_ancestor = mainFrame;
        m_editSimProppertiesController = new EditSimulationPropertiesController(m_ancestor.getManager());
        run();

    }

    private void run() {

        int check = m_editSimProppertiesController.editSimulationProperties();

        if (check == -1) {
            JOptionPane.showMessageDialog(this, "Can't view or edit properties. There is no active project.", "No active project", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else if (check == -2) {
            JOptionPane.showMessageDialog(this, "Can't view or edit properties. There is no active simulation.", "No active simulation", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else if (check == -3) {
            JOptionPane.showMessageDialog(this, "Can't view or edit properties.", "Error", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else {

            m_oldName = m_editSimProppertiesController.getOldName();
            m_oldDescription = m_editSimProppertiesController.getOldDescription();
            initComponents();
            setContentPane(new EditSimulationPropertiesPane(this, m_oldName, m_oldDescription));
            setLocationRelativeTo(null);
            setVisible(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void newProperties(String newName, String newDescription) {
        if (m_editSimProppertiesController.setNewProperties(newName, newDescription)) {

            JOptionPane.showMessageDialog(this, "Simulation properties changed.", "Simulatin Properties", JOptionPane.INFORMATION_MESSAGE);
            //setVisible(false);
            dispose();
        } else {

            JOptionPane.showMessageDialog(this, "A simulation with the same name exists. Please choose a diferente name.", "Simulatin Properties", JOptionPane.ERROR_MESSAGE);

        }

    }
}
