/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadnetwork.gui;

import javax.swing.JOptionPane;
import roadnetwork.controllers.NewProjectController;

/**
 *
 * @author André Pedrosa, Hélder Faria, José Miranda, Rubén Rosário
 */
public class NewProjectFrame extends javax.swing.JFrame {

    MainFrame m_mainFrame;
    NewProjectController m_newProjectController;

    /**
     * Creates new form JanelaNewProject
     */
    public NewProjectFrame(MainFrame frame) {
        m_mainFrame = frame;
        m_newProjectController = new NewProjectController(m_mainFrame.getManager());
        m_newProjectController.newProject();
        initComponents();
        setContentPane(new NewProjectPane(this));
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Project");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void createProject(String name, String description) {
        m_newProjectController.setProjectName(name);
        if (m_newProjectController.setProjectDescription(description)) {
            JOptionPane.showMessageDialog(this, "Project \"" + name + "\" has been created and is now active");
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "The was an error. Project nor created!");
            setVisible(false);
        }
    }
}
