/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadnetwork.gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import roadnetwork.controllers.ShowVehiclesController;
import roadnetwork.domain.Vehicle;

/**
 *
 * @author josemiranda
 */
public class ShowVehiclesDialog extends javax.swing.JDialog {

    private MainFrame m_ancestor;
    private ShowVehiclesController m_showVehiclesController;
    private ArrayList<Vehicle> m_vehiclesList;
    
    /**
     * Creates new form ShowVehiclesDialog
     */
    public ShowVehiclesDialog(MainFrame mainFrame, boolean modal) {
        super(mainFrame, modal);
        m_ancestor=mainFrame;
        m_showVehiclesController= new ShowVehiclesController(m_ancestor.getManager());
        run();
    }
    
    private void run() {
        if (!m_showVehiclesController.projectActive()) {
            JOptionPane.showMessageDialog(this, "Can't show Vehicles. There is no active project.", "No active project", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else {
            m_vehiclesList = m_showVehiclesController.getVehiclesList();
            if (m_vehiclesList == null) {
                JOptionPane.showMessageDialog(this, "Can't show Vehicles. The current project does't contain vehicles.", "No vehicles", JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
            } else {
                initComponents();
                setContentPane(new ShowVehiclesPane(this, m_vehiclesList));
                setLocationRelativeTo(null);
                setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
