/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roadnetwork.gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import roadnetwork.controllers.VehiclesComparisonAnalysisController;
import roadnetwork.domain.Vehicle;

/**
 *
 * @author josemiranda
 */
public class VehicleComparisonFrame extends javax.swing.JFrame {

    MainFrame m_mainFrame;
    VehiclesComparisonAnalysisController m_vComparisonAnalysisController;
    ArrayList<Vehicle> m_vehiclesList;
    
    /**
     * Creates new form JanelaVehicleComparison
     * @param frame
     */
    public VehicleComparisonFrame(MainFrame frame) {
        m_mainFrame=frame;
        m_vComparisonAnalysisController = new VehiclesComparisonAnalysisController(m_mainFrame.getManager());
        
        run();
    }
    
    private void run(){
        if (!m_vComparisonAnalysisController.projectActive()) {
            JOptionPane.showMessageDialog(this, "Can't analyse network. There is no active project.", "No active project", JOptionPane.INFORMATION_MESSAGE);
            setVisible(false);
        } else if (m_vComparisonAnalysisController.newAnalysis()) {
            //get the active project's list of vehicles
            m_vehiclesList = m_vComparisonAnalysisController.newVehicleComparisonAnalysis();
            initComponents();
            setLocationRelativeTo(null);

            setContentPane(new VehicleComparisonChooseVehiclesPane(this, m_vehiclesList));
            pack();
            setVisible(true);
        } else {
            JOptionPane.showMessageDialog(m_mainFrame, "The active project can not be analysed at this point!", "Error", JOptionPane.WARNING_MESSAGE);
            setVisible(false);
        }
    }
    
    public void setVehiclesList(ArrayList<Vehicle> vlist){
        m_vComparisonAnalysisController.setVehiclesList(vlist);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vehicle Comparison");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
